def c_class(class_name: str, parent_class_name: str, class_body: str, namespace: str = None) -> str:
    return f"""
// Generated by GDScriptToCSharpTypeConverter by Benjamin Eklund
{f"namespace {namespace};" if namespace else ""}

using Godot;
using static Godot.GD;
using System;
    
public partial class {class_name} : Node {{
    [Export] public {parent_class_name} WrappedNode;
    {class_body}
}}
    """
